### ISSUE TITLE
rsa default min size

### ISSUE THREAD

**Issue by flaviotorres** [ojarva/python-sshpubkeys#18]
Hi,

Thank you for sharing! We're using it to validate our public keys and I hope make our "public-key system management" Open Source soon.

BTW, I believe the new default min size for rsa keys is now 2048 bits. How about upgrade the default min value to 2048 ?

Thank you,

**Comment by ojarva** [comment]
Glad to hear this has been useful for you! Please tell me (send email/open an issue/comment to this issue) if you manage to release your software at some point.

The default for generating RSA keys is 2048 bits, but newest OpenSSH release still accepts 768 bits (http://www.openssh.com/txt/release-7.3).

Of course, using 768 bit RSA keys is a bad idea, but it is still allowed by OpenSSH, and other SSH servers as well (I guess). This library should only validate the keys, and provide related information, not enforce secure keys. Same goes for disallowing short DSA keys etc. So the code using this library should make additional checks, such as whether key length matches to their standards and whether key type is actually accepted by them.

Does this make any sense to you?

**Comment by flaviotorres** [comment]
Hi,

You are absolutely right! So that's what I'm doing, making additional checks, what's pretty easy with your lib.

I'll let you know soon,

Thank you again!
