### ISSUE TITLE
Commented out lines throw exception

### ISSUE THREAD

**Issue by Rocco83** [ojarva/python-sshpubkeys#21]
Hi,

commented lines gives this error:

Traceback (most recent call last):
[...]
    ssh_obj.parse()
  File "[...]/sshpubkeys/__init__.py", line 399, in parse
    key_parts = self._split_key(keydata)
  File "[...]/sshpubkeys/__init__.py", line 206, in _split_key
    self.options = self.parse_options(self.options_raw)
  File "[...]/sshpubkeys/__init__.py", line 267, in parse_options
    parse_add_single_option(opt)
  File "[...]/sshpubkeys/__init__.py", line 240, in parse_add_single_option
    raise InvalidOptionNameException("%s is not valid option name." % opt_name)
sshpubkeys.exceptions.InvalidOptionNameException: #ssh-rsa is not valid option name.

**Comment by ojarva** [comment]
Can you clarify when you get this error? `#ssh-rsa` is indeed not a valid public key line. The library does not handle parsing full `authorized_keys` files (including empty and commented-out lines) - that you have to either implement and create a new pull request, or handle on your own code.

**Comment by Rocco83** [comment]
Absolutely clear :) closing this issue, opening a new one to handle fully the files authorized_keys file.
