### ISSUE TITLE
Malformed exception on "good" key

### ISSUE THREAD

**Issue by mujihina** [ojarva/python-sshpubkeys#30]
Hi,
   The key below works, but sshpubkeys certainly doesn't like it.  Any suggestions?

ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAxmlwW50PufyAgHkLehNP4xHnSumqnfrKtW9fIzw2TLP8zfOCyUZFqCfXhegtV22a4wqPOJu4KYU6q1QEnWJtQwJiwtmoCBWOd8zi0OpgNEwxMnJfMGircwZPWPL1+wKiYRiXWsujtu8bAfNBFbx2rfKyv4yxhQoZQFrmjsJhWrLx7fCb5Yq7965c4A0YHrAyffx8k+Fh1UrwUfpTtP+Tr7UV2Vq8bYz9SM+1dmO8UTvWjsvizSMJN6sBdH1h7xdAGIrDUTke3UF8Pp/zyLtpUzfHzbbzW7p5oj89P/0WZnTZsIc0c4KHkmn9O8/fsW6qAxijEz2nU/OtH1A3iLJyNw==

Thanks.

**Comment by ojarva** [comment]
Thanks, I'll have a look.

**Comment by ojarva** [comment]
This key seems to work just fine:

```
from sshpubkeys import SSHKey
sshkey = SSHKey("ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAxmlwW50PufyAgHkLehNP4xHnSumqnfrKtW9fIzw2TLP8zfOCyUZFqCfXhegtV22a4wqPOJu4KYU6q1QEnWJtQwJiwtmoCBWOd8zi0OpgNEwxMnJfMGircwZPWPL1+wKiYRiXWsujtu8bAfNBFbx2rfKyv4yxhQoZQFrmjsJhWrLx7fCb5Yq7965c4A0YHrAyffx8k+Fh1UrwUfpTtP+Tr7UV2Vq8bYz9SM+1dmO8UTvWjsvizSMJN6sBdH1h7xdAGIrDUTke3UF8Pp/zyLtpUzfHzbbzW7p5oj89P/0WZnTZsIc0c4KHkmn9O8/fsW6qAxijEz2nU/OtH1A3iLJyNw==")
sshkey.bits  # 2048
sshkey.key_type  # ssh-rsa
```

Which python version are you using? Are you sure you did not have any additional line breaks / spaces / invisible unicode characters?

**Comment by mujihina** [comment]
Apologies.  I copy pasted the wrong key. in my original comment :( 
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAtathUt/0xo5oIaZOPRubxdsDnsKNuamo1e6l3bvSlOxMCwh0OTHCZ+CG7VAeCtqBFC386FAyCVIHfziins+pv3JWmZW4KQkN5eL3f5sYNhWtlIBTWPKtKk+fZ9RdGU9Kq3cqThJupFGome9IHoEkTfs0B+wVCfBnoZ657V5rOe+DpPfD0dvKQ0EelbFCm3pLrYQvgk183MpJ3MbJbc04Lk7mpfKGmqgm3w4rZKEt4E6Z6j2guNS8lndv7Dp3Yr+63JcLHhaKXENCbsRIM9Z2vY+QPzIRE2Hgwe56QyP0Ukm74OZTop5E7iRZZhzFxsN1yqpHNkv9y359eg1DZvQ==



Python 3.5.3 (default, Apr 19 2017, 15:00:50) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> from sshpubkeys import SSHKey
>>> ssh = SSHKey("ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAtathUt/0xo5oIaZOPRubxdsDnsKNuamo1e6l3bvSlOxMCwh0OTHCZ+CG7VAeCtqBFC386FAyCVIHfziins+pv3JWmZW4KQkN5eL3f5sYNhWtlIBTWPKtKk+fZ9RdGU9Kq3cqThJupFGome9IHoEkTfs0B+wVCfBnoZ657V5rOe+DpPfD0dvKQ0EelbFCm3pLrYQvgk183MpJ3MbJbc04Lk7mpfKGmqgm3w4rZKEt4E6Z6j2guNS8lndv7Dp3Yr+63JcLHhaKXENCbsRIM9Z2vY+QPzIRE2Hgwe56QyP0Ukm74OZTop5E7iRZZhzFxsN1yqpHNkv9y359eg1DZvQ==")
>>> ssh.parse()
Traceback (most recent call last):
...
sshpubkeys.exceptions.MalformedDataException: Requested 257 bytes, but only 255 bytes available.

**Comment by ojarva** [comment]
No problem.

Curiously my openssh says this is not a valid key:

```
$ ssh-keygen -l -f test_key.txt 
test_key.txt is not a public key file.
```

ssh -V: `OpenSSH_7.4p1, LibreSSL 2.5.0`, same result for older OpenSSH: `OpenSSH_6.9p1 Ubuntu-2ubuntu0.2, OpenSSL 1.0.2d 9 Jul 2015`. Especially for strict mode (tries to only accepts what ssh-keygen accepts), the key should be refused.

I don't understand why key specifies data length > actual data length, so I don't know what would be the right way to accept this key in loose mode. Truncating specified data length to actual data length works, but then actually malformed keys are accepted as well.
