### ISSUE TITLE
3.2.0 Incompatible with python 2.7

### ISSUE THREAD

**Issue by dylanmann** [ojarva/python-sshpubkeys#79]
Hello, it appears your recent release is incompatible with python 2.7, however it is possible to install using pip2.  Can you either fix this incompatibility or disallow installation on python 2.7 using [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires)?

## Steps to reproduce:
`pip2 install sshpubkeys==3.2.0`
`python2`
`import sshpubkeys`

```
Python 2.7.16 (default, Jul 10 2019, 03:39:20)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sshpubkeys
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/sshpubkeys/__init__.py", line 2, in <module>
    from .keys import *  # pylint:disable=wildcard-import
  File "/usr/local/lib/python2.7/site-packages/sshpubkeys/keys.py", line 176
    raise MalformedDataError("Unable to unpack %s bytes from the data" % self.INT_LEN) from ex
                                                                                          ^
SyntaxError: invalid syntax
```

**Comment by ojarva** [comment]
Let's do that. I have no intention to support python 2.7, which reached EOL over a year ago.

**Comment by omerlevko** [comment]
@ojarva can you please mark release 3.2 also as python 2.7 incompatible using python_requires?

**Comment by ojarva** [comment]
Releases are immutable. I yanked 3.2 from pypi but if you have pinned it, pip (or whatever tool you are using) will still use it.
