### ISSUE TITLE
SSHKey() does not handle authorized_keys format well

### ISSUE THREAD

**Issue by jubalfh** [ojarva/python-sshpubkeys#8]
I guess you might not think it a bug at all: `SSHKey()` throws an exception (_Unable to decode the key_), when fed with a line that contains authorized_keys data (options followed by key type, key data and comment).

Would you accept a patch/PR with an implementation of such feature?

**Comment by ojarva** [comment]
@jubalfh sorry about not answering earlier - I completely missed these. I think these should be parsed properly (but currently are not). I would accept PR with an implementation of this.

**Comment by ojarva** [comment]
I added formatting and some tests for this. The implementation is a bit hack-ish, so feel free to improve it.
