### ISSUE TITLE
Question: Support for python typing

### ISSUE THREAD

**Issue by manfred-kaiser** [ojarva/python-sshpubkeys#87]
Are you interested in supporting [typing](https://docs.python.org/3.5/library/typing.html)?

If you are interested, I will add type hints.

**Comment by ojarva** [comment]
Typing is nice; I just haven't got a need to add that by myself (and it wasn't well supported when I got started with this). So go ahead, a PR with good typing hints will go in straight away.

**Comment by ojarva** [comment]
This has been open for some time with no related PR & no issue is needed for this PR. Closing this doesn't mean PR adding type hints isn't appreciated.
