### ISSUE TITLE
Issue with parse function

### ISSUE THREAD

**Issue by ajoseph-godaddy** [ojarva/python-sshpubkeys#93]
Using the latest version I am having a problem using the parse function that was working under python2 previously. 
```Traceback (most recent call last):
  File "/opt/ssh_key_deploy.py", line 321, in <module>
    main()
  File "/opt/ssh_key_deploy.py", line 316, in main
    key_deploy.get_ssh_keys()
  File "/opt/ssh_key_deploy.py", line 191, in get_ssh_keys
    ssh.parse()
  File "/usr/local/lib/python3.9/site-packages/sshpubkeys/keys.py", line 457, in parse
    if keydata.startswith("---- BEGIN SSH2 PUBLIC KEY ----"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
Do you have any thoughts or assistance?

**Comment by ajoseph-godaddy** [comment]
Nothing, I am just trying to use the package under python 3.9

**Comment by ajoseph-godaddy** [comment]
@ojarva any chance you have looked at this and have a solution? I have tried Amazon Linux 2023 and AlmaLinux 9 (both on AWS) and both have the same error.

**Comment by ojarva** [comment]
Hi @ajoseph-godaddy ,

python 3.9 tests which have quite a bunch of different types of keys seems to work just fine.

If your input to "what are you doing to get an error with python 3.9" is "nothing", then there's absolutely nothing for me to do - I have no clue what you're doing, as the library seems to work fine under 3.9.

If you are able to provide a **minimal** example that fails under 3.9, then there are higher chances of something happening.

**Comment by ojarva** [comment]
As you closed this as fixed, I assume the issue was on your code. 👍

**Comment by ajoseph-godaddy** [comment]
Yes, sorry. Once you verified that the service was working I went back and understood the issue better. Found out that S3 was returning a bytes object instead of a string object. While this could be handled inside your code it was easier for me to just force it to a string before calling the module.
